name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  TINYGO_VERSION: "0.25.0"
  
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: go mod tidy
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "Run 'go mod tidy' and push it"
          exit 1
        fi

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        
    - name: Build
      run: make build
      
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:   
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3     
    - name: Run unit tests
      run: make test

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run integration tests
      run: make test-integration

  security:
    name: Code scanning
    runs-on: ubuntu-latest
    steps:  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3    
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      continue-on-error: true
      with:
        args: ./...    
    - name: Lint
      uses: golangci/golangci-lint-action@v3.2.0
      continue-on-error: true
      with:
        version: v1.49
        args: --deadline=30m
        skip-cache: true 
    - uses: dominikh/staticcheck-action@v1.2.0
      continue-on-error: true
      with:
        version: "2022.1"

  semgrep-sast:
    name: SAST with semgrep
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci
        env:
           # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable. 
           SEMGREP_RULES: p/default # more at semgrep.dev/explore

  image:
    name: Image scanning
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3    
    - name: Build image
      run: make build-image                    
    - name: Trivy vulnerability scanner
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'krol/demo:demo'
        scan-ref: '.'
        trivy-config: trivy.yaml   