name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
env:
  TINYGO_VERSION: "0.25.0"
  
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: go mod tidy
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "Run 'go mod tidy' and push it"
          exit 1
        fi

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        
    - name: Build
      run: make build
      
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:   
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3     
    - name: Run unit tests
      run: make test

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run integration tests
      run: make test-integration

  security:
    name: Code security
    runs-on: ubuntu-latest
    steps:  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3    
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      continue-on-error: true
      with:
        args: ./...    
    - name: Lint
      uses: golangci/golangci-lint-action@v3.2.0
      continue-on-error: true
      with:
        version: v1.49
        args: --deadline=30m
        skip-cache: true # https://github.com/golangci/golangci-lint-action/issues/244#issuecomment-1052197778
    - uses: dominikh/staticcheck-action@v1.2.0
      continue-on-error: true
      with:
        version: "2022.1"            